name: setup-trigger

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:    
#       - main
#   push:
#     branches:
#       - main
#   repository_dispatch:
#     types: [golang]

inputs:
  app_name:
    description: 'APP_NAME'
    required: true
  username:
    description: 'user name'
    required: true
  password:
    description: 'password'
    required: true
runs: 
  using: "composite"
  steps:
  - run: echo "hello"
    shell: bash
jobs:
  job1:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
        
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Login to DockerHub
#       uses: docker/login-action@v1 
#       with:
#         username: ${{ inputs.username }}
#         password: ${{ inputs.password }}
    - run : |-
        echo Hello
      shell: bash
#     - name: Build and push
#       uses: docker/build-push-action@v4
#       with:
#         context: ./
#         push: true
#         tags: "${{ inputs.app_name }}/app:latest"
#         cache-from: type=gha, scope=abc
#         cache-to: type=gha, mode=max, scope=abc
  job2:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - run : |-
        echo Hello
      shell: bash
