name: setup-trigger

inputs:
  app_name:
    description: 'APP_NAME'
    required: true
  username:
    description: 'user name'
    required: true
  password:
    description: 'password'
    required: true

runs: 
  using: "composite"
  steps:
  - run: echo "hello"
    shell: bash

jobs:
  job1:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    inputs:
      app_name: ${{ inputs.app_name }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
    env:
      TEST: ${{ inputs.password }}
    steps:
      - run: |
          echo $TEST
        shell: bash
