name: setup-trigger

inputs:
  app_name:
    description: 'APP_NAME'
    required: true
  username:
    description: 'user name'
    required: true
  password:
    description: 'password'
    required: true

env:
  TEST: ${{ inputs.password }}

runs: 
  using: "composite"
  steps:
  - run: echo "hello"
    shell: bash

jobs:
  job1:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
    - run : |-
        echo $TEST
      shell: bash
