name: test

on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:    
#       - main
#   push:
#     branches:
#       - main
  repository_dispatch:
    types: [golang]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Services
      uses: actions/checkout@v2
      with: 
        repository: haomapu/${{ github.event.client_payload.type }}
        ref: main
        path: ./
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ github.event.client_payload.username }}
        password: ${{ github.event.client_payload.password }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./
        push: true
        tags: "${{ github.event.client_payload.branch }}/app:latest"
        cache-from: type=gha, scope=abc
        cache-to: type=gha, mode=max, scope=abc
        
