name: test

on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:    
#       - main
#   push:
#     branches:
#       - main
  workflow_call:
    inputs:
      app_name:
        description: 'APP_NAME'
        required: true
        type: string
      username:
        description: 'user name'
        required: true
        type: string
      password:
        description: 'password'
        required: true
        type: string

jobs:
  job1:
    name: Setup, Build, Publish
    permissions:
      contents: 'write'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo ${{ inputs.app_name }}
        shell: bash
