name: test

on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:    
#       - main
#   push:
#     branches:
#       - main
  workflow_call:
    inputs:
      app_name:
        description: 'APP_NAME'
        required: true
        type: string
      username:
        description: 'user name'
        required: true
        type: string
      password:
        description: 'password'
        required: true
        type: string

jobs:
  job1:
    name: Setup, Build, Publish
    permissions:
      contents: 'write'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to the Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{secrets.DOCKERHUB_USERNAME}}/app:latest"
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha,mode=max, scope=${{ github.workflow }}
